name: CI
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v6
    - uses: coursier/cache-action@v4.1
    - name: test
      run: sbt -v doc
